version: "3.9"

services:
  caddy:
    image: coloradostark/caddy-ssl-multisite:0.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-data:/var/www
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - db-variables.env
  wordpress:
    depends_on:
      - db
    image: wordpress:5.8
    restart: always
    env_file:
      - wp-variables.env
    volumes:
      - ./public-html:/var/www/html
volumes:
  www-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./www-data"
  db_data: {}
