version: "3.9"

services:
  caddy:
    image: caddy:2.5.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-data:/var/www
      - ./config:/etc/caddy
  db:
    image: mysql:8.0.15
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - db-variables.env
  wordpress:
    depends_on:
      - db
    image: wordpress:6.0
    restart: always
    env_file:
      - wp-variables.env
    volumes:
      - ./www-data:/var/www/html
volumes:
  www-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./www-data"
  db_data: {}
